// GENERATED by scripts/sync-tokens.mjs — do not edit by hand.
//
// Source: daoUI @ 8ef4cc5 (tokens.json)
// Regenerate: npm run sync-tokens
//
// The provenance line above is load-bearing. zhouyi carries a src/theme/
// colors.gen.ts whose first line reads "Extracted BY HAND from the daoUI asset
// catalogs" — a .gen filename over content no generator produced, and its
// sibling tokens.ts still cites KairosDesign, which daoUI superseded on
// 2026-07-09. A citation that cannot be followed reads exactly like one that
// can. This file can be followed: re-run the script and diff.

export const DAOUI_SOURCE_COMMIT = "8ef4cc5";

export const lightColors = {
  "txPrimary": "#191b18ff",
  "txSecondary": "#3d403bbf",
  "txTertiary": "#3d403b80",
  "txAccent": "#3281fff2",
  "txError": "#e34837f2",
  "txWarning": "#f18736f2",
  "txSuccess": "#6a8b5bf2",
  "txDisabled": "#3d403b38",
  "bgPrimary": "#3d403b14",
  "bgSecondary": "#3d403b08",
  "bgAccent": "#3281ff14",
  "bgWarning": "#f1873614",
  "bgError": "#e3483714",
  "bdBase": "#2c2721cc",
  "bdPrimary": "#3d403b26",
  "bdSecondary": "#3d403b14",
  "bdCard": "#91836e59",
  "bdAccent": "#3281ff59",
  "icPrimary": "#191b18e6",
  "icSecondary": "#3d403b99",
  "icAccent": "#3281ffe6"
} as const;

export const darkColors = {
  "txPrimary": "#fefffff2",
  "txSecondary": "#f3f6f8b3",
  "txTertiary": "#f3f6f880",
  "txAccent": "#3281fff2",
  "txError": "#ff4b4bf2",
  "txWarning": "#f18736f2",
  "txSuccess": "#6a8b5bf2",
  "txDisabled": "#f3f6f833",
  "bgPrimary": "#f3f6f814",
  "bgSecondary": "#f3f6f80d",
  "bgAccent": "#3281ff14",
  "bgWarning": "#f1873614",
  "bgError": "#ff4b4b14",
  "bdBase": "#000000ff",
  "bdPrimary": "#f3f6f826",
  "bdSecondary": "#f3f6f814",
  "bdCard": "#e6d3b226",
  "bdAccent": "#3281ff59",
  "icPrimary": "#f3f6f8e6",
  "icSecondary": "#f3f6f899",
  "icAccent": "#3281ffe6"
} as const;

export type ColorRole = keyof typeof lightColors;
